# Generated by Django 5.0.1 on 2024-01-29 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Руководитель не является участником своей команды.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participants",
                to="users.team",
                verbose_name="Команда",
            ),
        ),
    ]
