# Generated by Django 5.0.1 on 2024-01-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Название ИПР"
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания ИПР"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала работ по ИПР"),
                ),
                ("end_date", models.DateField(verbose_name="Дедлайн ИПР")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Выполнен"),
                            ("in_progress", "В работе"),
                            ("cancel", "Отменен"),
                            ("trail", "Отстает"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Статус ИПР",
                    ),
                ),
            ],
            options={
                "verbose_name": "ИПР",
            },
        ),
    ]
