# Generated by Django 5.0.1 on 2024-01-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipr", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipr",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ipr",
            name="ease_of_creation",
        ),
        migrations.RemoveField(
            model_name="ipr",
            name="usability",
        ),
        migrations.AlterField(
            model_name="ipr",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата начала работ по ИПР"
            ),
        ),
        migrations.AlterField(
            model_name="ipr",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "Выполнен"),
                    ("in_progress", "В работе"),
                    ("canceled", "Отменен"),
                    ("trail", "Отстает"),
                ],
                default=("complete", "Выполнен"),
                max_length=20,
                verbose_name="Статус ИПР",
            ),
        ),
    ]
