# Generated by Django 5.0.1 on 2024-01-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ipr",
            "0003_remove_ipr_description_remove_ipr_ease_of_creation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipr",
            name="creation_date",
        ),
        migrations.AlterField(
            model_name="ipr",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала работ по ИПР"),
        ),
        migrations.AlterField(
            model_name="ipr",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "Выполнен"),
                    ("in_progress", "В работе"),
                    ("cancel", "Отменен"),
                    ("trail", "Отстает"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="Статус ИПР",
            ),
        ),
    ]
