# Generated by Django 5.0.1 on 2024-02-03 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipr", "0005_ipr_creation_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ipr",
            constraint=models.UniqueConstraint(
                fields=("executor", "title"), name="unique_executor_title"
            ),
        ),
    ]
