# Generated by Django 5.0.1 on 2024-02-03 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipr", "0008_remove_ipr_unique_executor_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ipr",
            name="unique_executor_title",
        ),
        migrations.AddConstraint(
            model_name="ipr",
            constraint=models.UniqueConstraint(
                fields=("executor", "title"), name="unique_executor_title"
            ),
        ),
    ]
