version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: reamisd/backend_ipr:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
  gateway:
    image: nginx:latest
    depends_on:
      - backend
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - static:/static
      - media:/media
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./error.log:/var/log/nginx/error.log
      - ./access.log:/var/log/nginx/access.log