version: '3'

volumes:
  pg_data:
  static:
  media:
  nginx_conf:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: reamisd/backend_ipr:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
      - nginx_conf:/app/nginx/
      - ./django_logs.log:/app/log_file.log
  frontend:
    image: reamisd/frontend_ipr:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: nginx:latest
    depends_on:
      - backend
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - static:/static
      - media:/media
      - nginx_conf:/etc/nginx/conf.d/
      - ./error.log:/var/log/nginx/error.log
      - ./access.log:/var/log/nginx/access.log