# Generated by Django 5.0.1 on 2024-01-21 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IPR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название задачи",
                        max_length=100,
                        verbose_name="Название задачи",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Добавьте текст описания группы",
                        max_length=500,
                        verbose_name="Описание задачи",
                    ),
                ),
                (
                    "creationdate",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания задачи"
                    ),
                ),
                (
                    "startdate",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата начала работ по задаче",
                    ),
                ),
                (
                    "enddate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дедлайн задачи"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "Отсутствует"),
                            ("complete", "Выполнен"),
                            ("not_complete", "Не выполнен"),
                            ("in_progress", "В работе"),
                            ("cancel", "Отменен"),
                            ("trail", "Отстает"),
                        ],
                        default="Отсутствует",
                        max_length=20,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_task",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель задачи",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executor_task",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель задачи",
                    ),
                ),
                (
                    "skill",
                    models.ManyToManyField(
                        blank=True,
                        max_length=255,
                        to="tasks.skill",
                        verbose_name="Скилл задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задачa",
                "verbose_name_plural": "Задачa",
            },
        ),
    ]
