# Generated by Django 5.0.1 on 2024-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "verbose_name": "Задачa",
                "verbose_name_plural": "Задачa",
            },
        ),
        migrations.RenameField(
            model_name="task",
            old_name="date_create",
            new_name="creationdate",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="end_date",
            new_name="enddate",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="start_date",
            new_name="startdate",
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(
                help_text="Добавьте текст описания группы",
                max_length=500,
                verbose_name="Описание задачи",
            ),
        ),
    ]
