# Generated by Django 5.0.1 on 2024-01-31 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ipr", "0002_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель задачи",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель задачи",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="ipr",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="ipr.ipr",
                verbose_name="ИПР",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="skill",
            field=models.ManyToManyField(
                max_length=255, to="tasks.skill", verbose_name="Навык"
            ),
        ),
    ]
