# Generated by Django 5.0.1 on 2024-02-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="skill",
            field=models.ManyToManyField(
                blank=True,
                max_length=255,
                null=True,
                to="tasks.skill",
                verbose_name="Навык",
            ),
        ),
    ]
