# Generated by Django 5.0.1 on 2024-02-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="skill",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="task",
            name="skill",
            field=models.CharField(
                choices=[("hard", "Hard skill"), ("soft", "Soft skill")],
                default="hard",
                max_length=20,
                verbose_name="Статус задачи",
            ),
        ),
    ]
