# Generated by Django 5.0.1 on 2024-01-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_ipr_skill_remove_task_type_task_skill_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="skill",
        ),
        migrations.AddField(
            model_name="task",
            name="skill",
            field=models.ManyToManyField(
                blank=True,
                max_length=255,
                to="tasks.skill",
                verbose_name="Скилл задачи",
            ),
        ),
    ]
