# Generated by Django 5.0.1 on 2024-02-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_remove_task_skill_delete_skill_task_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="skill",
            field=models.CharField(
                choices=[("hard", "Hard skill"), ("soft", "Soft skill")],
                default="hard",
                max_length=20,
                verbose_name="Навык",
            ),
        ),
    ]
