# Generated by Django 5.0.1 on 2024-01-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_remove_task_skill_task_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="custom_enddate",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ваш срок выполнения"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="enddate_option",
            field=models.IntegerField(
                choices=[
                    (3, "3 месяца"),
                    (6, "6 месяцев"),
                    (0, "Введите свое значение"),
                ],
                default=0,
                verbose_name="Срок выполнения",
            ),
        ),
    ]
