# Generated by Django 5.0.1 on 2024-01-21 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_task_custom_enddate_task_enddate_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="custom_enddate",
        ),
        migrations.RemoveField(
            model_name="task",
            name="enddate_option",
        ),
    ]
